### ISSUE TITLE
关于main 函数的一点疑问

### ISSUE THREAD

**Issue by OC0311** [0x04C2/notes#15]
在您的那篇关于调度的文章中看到一句话

> main is a Goroutine

> 我们写的 main 函数在程序启动时，同样会以 Goroutine 身份被 Machine 执行

有个小疑问，按我的理解，和书上看到的。main 并不是一个goroutine  而是主goroutine 执行流程中的一个流程而已，主goroutine 是  m0 上的 g0 中的一个内部逻辑 。主goroutine 进行了一些初始化工作  才会去执行 main 函数。

**Comment by fuweid** [comment]
> runtime.schedinit 会在调用 procresize 时为 m0 分配上 allp[0]

https://github.com/golang/go/blob/048c9cfaacb6fe7ac342b0acd8ca8322b6c49508/src/runtime/proc.go#L3623-L3627

这个链接是 `procresize` 让没有 p 的 m去绑定一个 p。对于 m0 而言，它会去绑定一个 p。

在下面的汇编代码里，`runtime·newproc` 会创建 goroutine 来绑定我们我们写的 `main` 函数地址，然后在调用 `runtime·mstart` 去执行 goroutine, 这不就是一个 goroutine 吗？ 😄  

```
// set the per-goroutine and per-mach "registers"
        // save m->g0 = g0
        MOVQ    CX, m_g0(AX)
        // save m0 to g0->m
        MOVQ    AX, g_m(CX)

        ...
        CALL    runtime·args(SB)
        CALL    runtime·osinit(SB)
        CALL    runtime·schedinit(SB)

        // create a new goroutine to start program
        MOVQ    $runtime·mainPC(SB), AX        // entry
        PUSHQ   AX
        PUSHQ   $0      // arg size
        CALL    runtime·newproc(SB)

        ...
        // start this M
        CALL    runtime·mstart(SB)  <=== I'm here!

        MOVL    $0xf1, 0xf1  // crash
        RET
```

ping @PoormaJin

**Comment by fuweid** [comment]
@PoormaJin 我即将关闭这个issue, 如果还有问题的话，可以随时 repoen。
